before_install:
- sudo apt-add-repository -y "deb http://ppa.launchpad.net/mag-magwas/zorp/ubuntu
  quantal main"
- sudo apt-get update -qq
- sudo apt-get install debhelper autotools-dev devscripts dkms linux-headers-3.5.0-32-generic
  python dh-autoreconf
script:
- debuild -i -us -uc -b
- git clone https://github.com/magwas/zorp.git -b identity ../identity
- ../identity/buildForLaunchpad
env:
  global:
    secure: CH8P2tBMvBTfAvEa8twb3CF90VLD3FjT6vPCRUt0hAdHv4FTzwsas9VUNUWFFp+LqC3Pr2ehoJdi98WtA9IxXaV14zgbGCCksZXQPwp3P4bIAjXBVglgj4elLJd2RGTMBZ10z2/LRZ+ozECEEQ9s80QDcGYvZ1ZO7wtJXNai21U=
