language: c
compiler:
 - gcc
before_install:
  - echo "deb http://download.opensuse.org/repositories/home:/VPetya:/zorp/xUbuntu_12.04/ ./" | sudo tee -a /etc/apt/sources.list
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_12.04/ /' >> /etc/apt/sources.list.d/osc.list"
  - wget -qO - http://download.opensuse.org/repositories/home:/VPetya:/zorp/xUbuntu_12.04/Release.key | sudo apt-key add -
  - wget -qO - http://download.opensuse.org/repositories/openSUSE:Tools/xUbuntu_12.04/Release.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install libboost-test-dev
  - wget http://cz.archive.ubuntu.com/ubuntu/pool/main/a/automake/automake1.4_1.4-p6-13.1_all.deb
  - wget http://cz.archive.ubuntu.com/ubuntu/pool/main/a/autoconf/autoconf_2.69-6_all.deb
  - sudo dpkg -i autoconf_2.69-6_all.deb
  - sudo dpkg -i automake1.4_1.4-p6-13.1_all.deb
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo apt-get update -qq
  - sudo apt-get install debhelper autotools-dev devscripts dkms linux-headers-generic python dh-autoreconf
  - echo -e "" | sudo apt-get install osc

script:
  - sudo apt-get install -qq devscripts equivs
  - sudo mk-build-deps -i
  - autoreconf -i
  - ./configure
  - sudo make check | true

after_success:
  - dpkg-buildpackage -S
  - echo -e "addFilter(\".*\") \n" > ../kzorp.rpmlintrc
  - cp rpm/* ../
  - echo -e "[general]\napiurl = https://api.opensuse.org\n[https://api.opensuse.org]\nuser = VPetya\npass = $PASS\n" > ~/.oscrc
  - osc co security:Zorp:LBaaS
  - rm security:Zorp:LBaaS/kzorp/*
  - mv ../*.* security:Zorp:LBaaS/kzorp
  - cd security:Zorp:LBaaS/kzorp
  - osc addremove
  - osc commit -m "TRAVIS"
env:
  global:
    secure: XdkJxQ0+N6biQX1O9jmWt1t8y2H6sNxef/QMQrlsJEYgYqnageRyRZ7r/vPtSOEmjLEF3op1Afh5V8xJrerDxGCLLG3HjmlGt2GfPW8/vDcohO/xVPKqaNT41OZrnzDs5PfJFjkVXLvqzBi7/dfUXHRFaiy9fZKtkYaBUtkmTX8=

